version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  backet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5020:80"


  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5030:80"
    depends_on:
       - catalog.api

